version: "3"
services:
  mqtt_slave:
    deploy:
      mode: replicated
      replicas: 6
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
        reservations:
          cpus: '0.10'
          memory: 32M
      restart_policy:
        condition: any
        delay: 5s
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: pause
        monitor: 60s
        max_failure_ratio: 0.3
    ports:
      - 1883:1883 # MQTT
      - 8080:8080 # MQTT WebSockets
      - 8888:8888 # HTTP
    image: chrisns/docker-vernemq:mergedhacks
    environment:
      - PEER_DISCOVERY_NAME=mqtt_slave
      - DOCKER_VERNEMQ_ALLOW_ANONYMOUS=on
      - DOCKER_VERNEMQ_ALLOW_MULTIPLE_SESSIONS=on