version: "3"
services:
  mqtt:
    networks:
      proxy:
      default:
        aliases:
          - mymqtt
    volumes:
      - data:/data
    deploy:
      replicas: 4
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.serviceDomain=mqtt.p.cns.me
        - com.df.servicePath=/
        - com.df.port=8080
        - com.df.httpsOnly=true
        - com.df.xForwardedProto=true
      resources:
        limits:
          cpus: '2.0'
          memory: 256M
        reservations:
          cpus: '0.10'
          memory: 96M
      restart_policy:
        condition: any
        delay: 5s
      update_config:
        parallelism: 1
        delay: 30s
        failure_action: pause
        monitor: 30s
        max_failure_ratio: 0.3
    stop_grace_period: 30s
    ports:
      - 1883:1883 # MQTT
#      - 8080:8080 # MQTT WebSockets
#      - 8888:8888 # HTTP
    image: pinked/docker-vernemq
    environment:
      - PEER_DISCOVERY_NAME=mymqtt
      - DOCKER_VERNEMQ_ALLOW_MULTIPLE_SESSIONS=on
      - DOCKER_VERNEMQ_QUEUE_DELIVER_MODE=balance

networks:
  default:
    external: false
  proxy:
    external: true

volumes:
  data:
    driver: glusterfs
